import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const exportToPdf = (state: any) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(22);
  doc.setTextColor(15, 23, 42); // slate-900
  doc.text("B-BBEE Scorecard Certificate", 105, 20, { align: "center" });
  
  doc.setFontSize(12);
  doc.setTextColor(100, 116, 139); // slate-500
  doc.text(`Client: ${state.client.name}`, 105, 30, { align: "center" });
  doc.text(`Financial Year: ${state.client.financialYear}`, 105, 36, { align: "center" });

  // Summary box
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.setFillColor(248, 250, 252); // slate-50
  doc.roundedRect(14, 45, 182, 35, 3, 3, "FD");
  
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text(`B-BBEE Status: Level ${state.scorecard.isDiscounted ? state.scorecard.discountedLevel : state.scorecard.achievedLevel}`, 20, 55);
  doc.text(`Total Score: ${state.scorecard.total.score.toFixed(2)} Points`, 20, 65);
  doc.text(`Recognition Level: ${state.scorecard.recognitionLevel}`, 20, 75);

  // Table
  autoTable(doc, {
    startY: 90,
    head: [["Element", "Target", "Score Achieved", "Sub-minimum Met"]],
    body: [
      ["Ownership", state.scorecard.ownership.target.toString(), state.scorecard.ownership.score.toFixed(2), state.scorecard.ownership.subMinimumMet ? "Yes" : "No"],
      ["Management Control", state.scorecard.managementControl.target.toString(), state.scorecard.managementControl.score.toFixed(2), "N/A"],
      ["Skills Development", state.scorecard.skillsDevelopment.target.toString(), state.scorecard.skillsDevelopment.score.toFixed(2), state.scorecard.skillsDevelopment.subMinimumMet ? "Yes" : "No"],
      ["Preferential Procurement", state.scorecard.procurement.target.toString(), state.scorecard.procurement.score.toFixed(2), state.scorecard.procurement.subMinimumMet ? "Yes" : "No"],
      ["Enterprise Development", state.scorecard.enterpriseDevelopment.target.toString(), state.scorecard.enterpriseDevelopment.score.toFixed(2), "N/A"],
      ["Socio-Economic Development", state.scorecard.socioEconomicDevelopment.target.toString(), state.scorecard.socioEconomicDevelopment.score.toFixed(2), "N/A"],
      ["Total", state.scorecard.total.target.toString(), state.scorecard.total.score.toFixed(2), state.scorecard.isDiscounted ? "Failed" : "Passed"]
    ],
    theme: 'grid',
    headStyles: { fillColor: [16, 185, 129] }, // emerald-500
    styles: { fontSize: 10, cellPadding: 6 },
    alternateRowStyles: { fillColor: [248, 250, 252] }
  });

  // Footer
  const pageHeight = doc.internal.pageSize.height || doc.internal.pageSize.getHeight();
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184); // slate-400
  doc.text("Generated by Okiru Companion B-BBEE Platform", 105, pageHeight - 15, { align: "center" });

  const fileName = `${state.client.name.replace(/\s+/g, '_')}_BBBEE_Certificate.pdf`;
  doc.save(fileName);
};
