import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { MeetingDetails } from "./meetingMinutesApi";
import { getMeetingTypeLabel, getPlatformLabel } from "./meetingMinutesApi";

const PRIMARY = [37, 99, 235] as [number, number, number];
const DARK = [17, 24, 39] as [number, number, number];
const MUTED = [107, 114, 128] as [number, number, number];
const LIGHT_BG = [249, 250, 251] as [number, number, number];
const BORDER = [229, 231, 235] as [number, number, number];

function addPageNumbers(doc: jsPDF) {
  const total = doc.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    const w = doc.internal.pageSize.getWidth();
    const h = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text(`Page ${i} of ${total}`, w / 2, h - 8, { align: "center" });
    doc.text("Generated by Okiru Companion", w - 14, h - 8, { align: "right" });
  }
}

function drawHRule(doc: jsPDF, y: number, margin: number) {
  const w = doc.internal.pageSize.getWidth();
  doc.setDrawColor(...BORDER);
  doc.setLineWidth(0.3);
  doc.line(margin, y, w - margin, y);
}

export function exportMeetingPdf(data: MeetingDetails): void {
  const { meeting, attendees, agendaItems, actionItems } = data;
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const margin = 14;
  const pageW = doc.internal.pageSize.getWidth();
  let y = margin;

  // ── Header ──────────────────────────────────────────────────────────────────
  doc.setFillColor(...PRIMARY);
  doc.rect(0, 0, pageW, 28, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(meeting.companyName.toUpperCase(), margin, 12);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  const subHeader = [
    meeting.companyRegistration ? `Reg: ${meeting.companyRegistration}` : null,
    meeting.companyAddress,
  ].filter(Boolean).join("  |  ");
  if (subHeader) doc.text(subHeader, margin, 18);

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text(getMeetingTypeLabel(meeting.meetingType).toUpperCase(), margin, 24);

  y = 34;

  // ── Meeting Info box ────────────────────────────────────────────────────────
  doc.setFillColor(...LIGHT_BG);
  doc.setDrawColor(...BORDER);
  doc.setLineWidth(0.4);
  doc.roundedRect(margin, y, pageW - margin * 2, 28, 2, 2, "FD");

  doc.setTextColor(...DARK);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");

  const col1x = margin + 4;
  const col2x = pageW / 2 + 2;
  let iy = y + 6;

  const infoRows: [string, string][] = [
    ["Date:", meeting.meetingDate],
    ["Time:", [meeting.startTime, meeting.endTime].filter(Boolean).join(" – ") || "N/A"],
    ["Venue:", meeting.venue || "Virtual"],
  ];
  const infoRows2: [string, string][] = [
    ["Platform:", getPlatformLabel(meeting.platform)],
    ["Chairperson:", meeting.chairperson],
    ["Company Secretary:", meeting.companySecretary],
  ];
  infoRows.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.text(label, col1x, iy);
    doc.setFont("helvetica", "normal");
    doc.text(value, col1x + 22, iy);
    iy += 6;
  });
  iy = y + 6;
  infoRows2.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.text(label, col2x, iy);
    doc.setFont("helvetica", "normal");
    doc.text(doc.splitTextToSize(value, 70)[0], col2x + 36, iy);
    iy += 6;
  });

  y += 32;

  // ── Executive Summary ───────────────────────────────────────────────────────
  if (meeting.aiExecutiveSummary) {
    y += 4;
    doc.setTextColor(...PRIMARY);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("EXECUTIVE SUMMARY", margin, y);
    y += 2;
    drawHRule(doc, y, margin);
    y += 5;

    doc.setTextColor(...DARK);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(meeting.aiExecutiveSummary, pageW - margin * 2);
    doc.text(lines, margin, y);
    y += lines.length * 4.5 + 4;
  }

  // ── Attendance Register ──────────────────────────────────────────────────────
  y += 2;
  doc.setTextColor(...PRIMARY);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("ATTENDANCE REGISTER", margin, y);
  y += 2;
  drawHRule(doc, y, margin);
  y += 4;

  const present = attendees.filter(a => a.attendanceStatus === "present");
  const apologies = attendees.filter(a => a.attendanceStatus === "apology");
  const absent = attendees.filter(a => a.attendanceStatus === "absent");

  if (present.length > 0) {
    autoTable(doc, {
      startY: y,
      head: [["#", "Name", "Position / Designation", "Role", "Status"]],
      body: present.map((a, i) => [
        String(i + 1),
        a.name,
        a.position || "–",
        a.role.charAt(0).toUpperCase() + a.role.slice(1),
        "Present",
      ]),
      margin: { left: margin, right: margin },
      styles: { fontSize: 8.5, cellPadding: 2.5, textColor: DARK },
      headStyles: { fillColor: PRIMARY, textColor: [255, 255, 255], fontStyle: "bold" },
      alternateRowStyles: { fillColor: LIGHT_BG },
      columnStyles: { 0: { cellWidth: 8 }, 3: { cellWidth: 26 }, 4: { cellWidth: 20 } },
    });
    y = (doc as any).lastAutoTable.finalY + 4;
  }

  if (apologies.length > 0) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...DARK);
    doc.text("Apologies:", margin, y);
    doc.setFont("helvetica", "normal");
    doc.text(apologies.map(a => `${a.name} (${a.position || a.role})`).join(", "), margin + 24, y);
    y += 6;
  }

  if (absent.length > 0) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...DARK);
    doc.text("Absent:", margin, y);
    doc.setFont("helvetica", "normal");
    doc.text(absent.map(a => `${a.name} (${a.position || a.role})`).join(", "), margin + 20, y);
    y += 6;
  }

  // ── Agenda & Minutes ─────────────────────────────────────────────────────────
  y += 4;
  doc.setTextColor(...PRIMARY);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("AGENDA AND MINUTES", margin, y);
  y += 2;
  drawHRule(doc, y, margin);
  y += 5;

  if (meeting.aiFormattedMinutes) {
    doc.setTextColor(...DARK);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    const minuteLines = doc.splitTextToSize(meeting.aiFormattedMinutes, pageW - margin * 2);
    minuteLines.forEach((line: string) => {
      if (y > doc.internal.pageSize.getHeight() - 20) {
        doc.addPage();
        y = margin + 4;
      }
      if (line.startsWith("RESOLVED:") || /^\d+\.\s/.test(line)) {
        doc.setFont("helvetica", "bold");
      } else {
        doc.setFont("helvetica", "normal");
      }
      doc.text(line, margin, y);
      y += 4.5;
    });
  } else {
    agendaItems.forEach((item) => {
      if (y > doc.internal.pageSize.getHeight() - 30) {
        doc.addPage();
        y = margin + 4;
      }
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...PRIMARY);
      doc.text(`${item.itemNumber}. ${item.title}`, margin, y);
      y += 5;

      if (item.discussionNotes) {
        doc.setFontSize(9);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(...DARK);
        const notesLines = doc.splitTextToSize(item.discussionNotes, pageW - margin * 2 - 4);
        doc.text(notesLines, margin + 4, y);
        y += notesLines.length * 4.5 + 2;
      }

      if (item.resolution) {
        doc.setFillColor(239, 246, 255);
        const resLines = doc.splitTextToSize(`RESOLVED: ${item.resolution}`, pageW - margin * 2 - 12);
        const boxH = resLines.length * 4.5 + 5;
        doc.roundedRect(margin + 2, y - 1, pageW - margin * 2 - 4, boxH, 1, 1, "F");
        doc.setFontSize(9);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(...PRIMARY);
        doc.text(resLines, margin + 6, y + 3);
        y += boxH + 3;
      }
      y += 4;
    });
  }

  // ── Action Items ─────────────────────────────────────────────────────────────
  if (actionItems.length > 0) {
    if (y > doc.internal.pageSize.getHeight() - 50) {
      doc.addPage();
      y = margin + 4;
    }
    y += 4;
    doc.setTextColor(...PRIMARY);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("ACTION ITEMS REGISTER", margin, y);
    y += 2;
    drawHRule(doc, y, margin);
    y += 4;

    const priorityColor = (p: string): [number, number, number] => {
      if (p === "high") return [254, 226, 226];
      if (p === "medium") return [254, 243, 199];
      return [220, 252, 231];
    };

    autoTable(doc, {
      startY: y,
      head: [["#", "Description", "Responsible", "Due Date", "Priority", "Status"]],
      body: actionItems.map((a, i) => [
        String(i + 1),
        a.description,
        a.responsiblePerson,
        a.dueDate || "TBC",
        a.priority.charAt(0).toUpperCase() + a.priority.slice(1),
        a.status.replace("_", " ").charAt(0).toUpperCase() + a.status.replace("_", " ").slice(1),
      ]),
      margin: { left: margin, right: margin },
      styles: { fontSize: 8.5, cellPadding: 2.5, textColor: DARK },
      headStyles: { fillColor: PRIMARY, textColor: [255, 255, 255], fontStyle: "bold" },
      alternateRowStyles: { fillColor: LIGHT_BG },
      columnStyles: { 0: { cellWidth: 8 }, 3: { cellWidth: 22 }, 4: { cellWidth: 20 }, 5: { cellWidth: 22 } },
      didParseCell: (hookData) => {
        if (hookData.section === "body" && hookData.column.index === 4) {
          const priority = (actionItems[hookData.row.index]?.priority ?? "medium").toLowerCase();
          hookData.cell.styles.fillColor = priorityColor(priority);
        }
      },
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  // ── Signature Blocks ──────────────────────────────────────────────────────────
  if (y > doc.internal.pageSize.getHeight() - 55) {
    doc.addPage();
    y = margin + 4;
  }

  y += 6;
  doc.setTextColor(...PRIMARY);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("CONFIRMATION OF MINUTES", margin, y);
  y += 2;
  drawHRule(doc, y, margin);
  y += 6;

  doc.setFontSize(9);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(...MUTED);
  doc.text("Signed as a true and correct record of proceedings:", margin, y);
  y += 10;

  const sigW = (pageW - margin * 2 - 10) / 2;
  const sigLineY = y + 14;

  // Chairperson block
  doc.setDrawColor(...BORDER);
  doc.setLineWidth(0.5);
  doc.line(margin, sigLineY, margin + sigW, sigLineY);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...DARK);
  doc.text("CHAIRPERSON", margin, sigLineY + 5);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.text(meeting.chairperson, margin, sigLineY + 10);
  doc.setTextColor(...MUTED);
  doc.text("Name / Signature / Date", margin, sigLineY + 15);

  // Company Secretary block
  const secX = margin + sigW + 10;
  doc.setDrawColor(...BORDER);
  doc.line(secX, sigLineY, secX + sigW, sigLineY);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...DARK);
  doc.text("COMPANY SECRETARY", secX, sigLineY + 5);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.text(meeting.companySecretary, secX, sigLineY + 10);
  doc.setTextColor(...MUTED);
  doc.text("Name / Signature / Date", secX, sigLineY + 15);

  addPageNumbers(doc);

  const safeName = meeting.companyName.replace(/[^a-zA-Z0-9]/g, "_");
  doc.save(`Meeting_Minutes_${safeName}_${meeting.meetingDate}.pdf`);
}
