import pptxgen from "pptxgenjs";

export const exportToPptx = async (state: any) => {
  const pres = new pptxgen();

  pres.layout = 'LAYOUT_16x9';

  // Master slide for branding
  pres.defineSlideMaster({
    title: "MASTER_SLIDE",
    background: { color: "FFFFFF" },
    objects: [
      { rect: { x: 0, y: 0, w: "100%", h: 0.5, fill: { color: "10B981" } } }, // Emerald top bar
      { text: { text: "Generated by Okiru Companion Platform", options: { x: 0.5, y: 7.0, w: 3, h: 0.5, color: "94A3B8", fontSize: 10 } } }
    ]
  });

  // Slide 1: Title
  const slide1 = pres.addSlide({ masterName: "MASTER_SLIDE" });
  slide1.addText(`B-BBEE Strategy & Scorecard`, { x: 1, y: 2.5, w: "80%", fontSize: 36, bold: true, color: "0F172A" });
  slide1.addText(`${state.client.name}`, { x: 1, y: 3.5, w: "80%", fontSize: 24, color: "64748B" });
  slide1.addText(`Financial Year: ${state.client.financialYear}`, { x: 1, y: 4.2, w: "80%", fontSize: 16, color: "64748B" });

  // Slide 2: Dashboard Overview
  const slide2 = pres.addSlide({ masterName: "MASTER_SLIDE" });
  slide2.addText("Current B-BBEE Status", { x: 0.5, y: 0.5, w: "90%", fontSize: 24, bold: true, color: "0F172A" });
  
  const currentLevel = state.scorecard.isDiscounted ? state.scorecard.discountedLevel : state.scorecard.achievedLevel;
  
  slide2.addShape(pres.ShapeType.rect, { x: 0.5, y: 1.5, w: 4, h: 2, fill: { color: "ECFDF5" } });
  slide2.addText("B-BBEE Level", { x: 0.8, y: 1.8, w: 3, h: 0.5, fontSize: 14, color: "065F46" });
  slide2.addText(`Level ${currentLevel}`, { x: 0.8, y: 2.3, w: 3, h: 0.8, fontSize: 32, bold: true, color: "047857" });
  
  slide2.addShape(pres.ShapeType.rect, { x: 5, y: 1.5, w: 4, h: 2, fill: { color: "F1F5F9" } });
  slide2.addText("Total Score", { x: 5.3, y: 1.8, w: 3, h: 0.5, fontSize: 14, color: "334155" });
  slide2.addText(`${state.scorecard.total.score.toFixed(2)} pts`, { x: 5.3, y: 2.3, w: 3, h: 0.8, fontSize: 32, bold: true, color: "0F172A" });

  if (state.scorecard.isDiscounted) {
    slide2.addText("Discounting principle applied due to sub-minimum failure.", { x: 0.5, y: 4, w: "90%", fontSize: 16, color: "EF4444", bold: true });
  } else {
    slide2.addText("All sub-minimums met successfully.", { x: 0.5, y: 4, w: "90%", fontSize: 16, color: "10B981" });
  }

  // Slide 3: Scorecard Breakdown (Table)
  const slide3 = pres.addSlide({ masterName: "MASTER_SLIDE" });
  slide3.addText("Scorecard Breakdown", { x: 0.5, y: 0.5, w: "90%", fontSize: 24, bold: true, color: "0F172A" });
  
  const tableData = [
    [{ text: "Element", options: { bold: true, fill: "10B981", color: "FFFFFF" } }, { text: "Score", options: { bold: true, fill: "10B981", color: "FFFFFF" } }, { text: "Target", options: { bold: true, fill: "10B981", color: "FFFFFF" } }],
    ["Ownership", state.scorecard.ownership.score.toFixed(2), state.scorecard.ownership.target.toString()],
    ["Management Control", state.scorecard.managementControl.score.toFixed(2), state.scorecard.managementControl.target.toString()],
    ["Skills Development", state.scorecard.skillsDevelopment.score.toFixed(2), state.scorecard.skillsDevelopment.target.toString()],
    ["Preferential Procurement", state.scorecard.procurement.score.toFixed(2), state.scorecard.procurement.target.toString()],
    ["Enterprise Development", state.scorecard.enterpriseDevelopment.score.toFixed(2), state.scorecard.enterpriseDevelopment.target.toString()],
    ["Socio-Economic Dev", state.scorecard.socioEconomicDevelopment.score.toFixed(2), state.scorecard.socioEconomicDevelopment.target.toString()],
  ];

  slide3.addTable(tableData, { x: 0.5, y: 1.5, w: 9, rowH: 0.6, fontSize: 14, border: { type: "solid", color: "E2E8F0" } });

  // Generate file
  const fileName = `${state.client.name.replace(/\s+/g, '_')}_BBBEE_Presentation`;
  await pres.writeFile({ fileName: fileName + ".pptx" });
};
